### ISSUE TITLE
Hi,支持spark2.3吗？你们集群运行起来了吗？

### ISSUE THREAD

**Issue by SelfEvoAI** [zngzlg/drelephant#1]
Hi,支持spark2.3吗？你们集群运行起来了吗？

**Comment by SelfEvoAI** [comment]
```
10-26-2018 11:14:26 INFO  [Thread-6] com.linkedin.drelephant.ElephantRunner : Fetching analytic job list...
10-26-2018 11:14:26 ERROR [Thread-6] com.linkedin.drelephant.ElephantRunner : Error fetching job list. Try again later...
java.net.MalformedURLException: no protocol: null?batch_num=10&applicationtype=MapReduce&version=1
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at com.linkedin.drelephant.analysis.AnalyticJobGeneratorTDW.fetchAnalyticJobs(AnalyticJobGeneratorTDW.java:93)
	at com.linkedin.drelephant.ElephantRunner$1.run(ElephantRunner.java:128)
	at com.linkedin.drelephant.ElephantRunner$1.run(ElephantRunner.java:90)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1900)
	at com.linkedin.drelephant.security.HadoopSecurity.doAs(HadoopSecurity.java:109)
	at com.linkedin.drelephant.ElephantRunner.run(ElephantRunner.java:90)
	at com.linkedin.drelephant.DrElephant.run(DrElephant.java:58)
```

部署了你的版本，报这个错误，你们遇到吗？有可能是什么原因啊？谢谢！！

**Comment by SelfEvoAI** [comment]
```
10-26-2018 15:33:30 ERROR [dr-el-executor-thread-0] com.linkedin.drelephant.ElephantRunner : javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[Unknown column 'name' in 'field list']
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:97)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:57)
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:66)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:448)
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:478)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:335)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveEnhanced(DefaultPersister.java:310)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:280)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveAssocManyDetails(DefaultPersister.java:851)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveMany(DefaultPersister.java:734)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveAssocMany(DefaultPersister.java:631)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:339)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveEnhanced(DefaultPersister.java:310)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:280)
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:248)
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1568)
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1558)
	at com.avaje.ebean.Ebean.save(Ebean.java:453)
	at play.db.ebean.Model.save(Model.java:91)
	at com.linkedin.drelephant.ElephantRunner$ExecutorJob.run(ElephantRunner.java:169)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'name' in 'field list'
	at sun.reflect.GeneratedConstructorAccessor36.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)
	at com.mysql.jdbc.Util.getInstance(Util.java:383)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2113)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2049)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2034)
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:205)
	at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:55)
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:134)
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:86)
	... 24 more
```

ftime是什么字段啊？现在又冒出来个name？

表结构需要怎么改吗？

**Comment by SelfEvoAI** [comment]
建议更新一下表结构  @zngzlg

**Comment by zngzlg** [comment]
更改了表结构，resource manager的REST接口也不是原来的了，要改的
