### ISSUE TITLE
数据导入后UI界面访问报错，帮忙看看可能是什么原因？谢谢！

### ISSUE THREAD

**Issue by SelfEvoAI** [zngzlg/drelephant#2]
```
[error] play - Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: No property found for [yarnAppHeuristicResultDetails] in expression yarnAppHeuristicResults.yarnAppHeuristicResultDetails
[error] application - 

! @79kohda7n - Internal server error, for (GET) [/search?id=application_1539842926807_26391] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: No property found for [yarnAppHeuristicResultDetails] in expression yarnAppHeuristicResults.yarnAppHeuristicResultDetails]]
	at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.2.jar:2.2.2]
Caused by: javax.persistence.PersistenceException: No property found for [yarnAppHeuristicResultDetails] in expression yarnAppHeuristicResults.yarnAppHeuristicResultDetails
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptor.buildElGetValue(BeanDescriptor.java:1717) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssoc.createElPropertyValue(BeanPropertyAssoc.java:126) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanPropertyAssocMany.buildElPropertyValue(BeanPropertyAssocMany.java:168) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptor.buildElGetValue(BeanDescriptor.java:1709) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptor.getElPropertyValue(BeanDescriptor.java:1677) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
	at com.avaje.ebeaninternal.server.deploy.BeanDescriptor.getElPropertyDeploy(BeanDescriptor.java:1670) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
```

![image](https://user-images.githubusercontent.com/12254857/47559149-58c4d480-d947-11e8-8eb4-fe9f09eb24b9.png)

**Comment by zngzlg** [comment]
这块改了之后只能支持后台高并发写入，UI是重写的，不再使用play框架了。

**Comment by SelfEvoAI** [comment]
哇，牛！UI都重写了。。。。你们重写的UI开源吗？官方的版本都不支持spark2.x，哎。。。
